import { route } from "../builders";
import type { ContentPage } from "../types";

/**
 * Route pages. Distances and times are approximate road figures — confirm with your suppliers
 * before launch. Amalfi Coast, Naples–coast distances/times come from published operator tables.
 * No prices are published until supplier rate cards exist.
 */

const ROME = { slug: "rome", label: "Rome" };
const FLORENCE = { slug: "florence", label: "Florence" };
const NAPLES = { slug: "naples", label: "Naples" };
const MILAN = { slug: "milan", label: "Milan" };

export const routePages: ContentPage[] = [
  /* ───────────── FROM ROME ───────────── */
  route({
    slug: "rome-to-naples-transfer",
    from: "Rome",
    to: "Naples",
    km: "about 225 km",
    drive: "about 2.5–3 hours",
    road: "A1 motorway (toll)",
    alt: "High-speed trains link the two city-centre stations in roughly 1 hour 15 minutes to 1 hour 30 minutes",
    pickups: "Fiumicino and Ciampino airports, Rome Termini station, Rome hotels",
    dropoffs: "Naples hotels, Napoli Centrale station, Capodichino airport, the cruise port",
    access:
      "Naples' historic centre has restricted-traffic zones and very narrow streets, so the driver drops you at the closest practical point.",
    stops: [
      ["Caserta Royal Palace", "an 18th-century palace and gardens just before Naples; allow 2–3 hours"],
      ["Montecassino Abbey", "a hilltop abbey visible from the A1, about 130 km from Rome"],
      ["Pompeii", "possible if you are continuing to the Amalfi Coast; adds roughly 3 hours"],
    ],
    insight: {
      heading: "Going on to the Amalfi Coast?",
      text: "Naples is the gateway to Sorrento, Positano and Amalfi. If that is your destination, book one combined Rome-to-Coast transfer instead of two separate legs: it avoids changing vehicles in Naples traffic and keeps your luggage in one place.",
    },
    parent: ROME,
    tags: ["rome", "naples"],
    related: ["rome-to-amalfi-coast-transfer", "naples-to-amalfi-coast-transfer", "rome-to-pompeii-transfer", "naples-airport-transfer"],
  }),
  route({
    slug: "rome-to-positano-transfer",
    from: "Rome",
    to: "Positano",
    km: "about 280 km",
    drive: "about 3.75–4.5 hours",
    road: "A1 and A3 motorways (toll), then the SS163 Amalfi Drive",
    alt: "Train to Naples or Salerno, then a ferry, SITA bus or taxi — several changes with luggage",
    pickups: "Fiumicino and Ciampino airports, Rome Termini station, Rome hotels",
    dropoffs: "Positano hotels and villas, the Marina Grande area",
    access:
      "Positano's centre is largely car-free and restricted in season. Municipal entry, parking and loading fees apply (they have been reported at €5 per entry, €15 per hour of parking and €8 for loading, and they change by season), so we itemise them in your quote and arrange the last stretch with a local operator when needed.",
    stops: [
      ["Naples", "a Neapolitan pizza lunch; adds about 1.5 hours"],
      ["Pompeii", "adds 2–3 hours including entry"],
      ["Vietri sul Mare", "the ceramics town where the Amalfi Coast begins"],
    ],
    insight: {
      heading: "Arrive with daylight to spare",
      text: "The final stretch of coast road is winding, and in peak season the last 20–30 km can take an hour or more. Evening arrivals are easier than midday ones in July and August. Tell us your hotel and we will confirm where the vehicle can stop and how many steps you will face with luggage.",
    },
    vehicles:
      "Sedans and vans are the right size for the Coast road. We rarely recommend minibuses unless your hotel is easily accessible; large luggage loads can travel in a second vehicle.",
    parent: ROME,
    tags: ["rome", "amalfi-coast"],
    related: ["rome-to-amalfi-coast-transfer", "rome-to-sorrento-transfer", "naples-to-positano-transfer", "amalfi-coast-alternate-license-plates"],
  }),
  route({
    slug: "rome-to-sorrento-transfer",
    from: "Rome",
    to: "Sorrento",
    km: "about 265 km",
    drive: "about 3.5 hours",
    road: "A1 and A3 motorways (toll), then the SS145 along the Sorrento peninsula",
    alt: "Train to Naples, then the Circumvesuviana line to Sorrento (about an hour from Naples)",
    pickups: "Fiumicino and Ciampino airports, Rome Termini station, Rome hotels",
    dropoffs: "Sorrento hotels, Marina Piccola ferry port, Piano di Sorrento and the wider peninsula",
    access:
      "Sorrento's centre is busy and partly pedestrian, and many hotels sit above steep lanes; we confirm the vehicle's access with the hotel beforehand.",
    stops: [
      ["Pompeii", "the most popular stop on this corridor; allow 2–3 hours"],
      ["Herculaneum", "a smaller, remarkably preserved Roman town; allow about 1.5 hours"],
      ["Naples", "a lunch stop and the National Archaeological Museum"],
    ],
    insight: {
      heading: "Timing the Capri ferry",
      text: "Most Capri hydrofoils and ferries leave from Sorrento's Marina Piccola. If you are connecting to one, tell us the ferry time and we schedule the transfer to arrive with a comfortable margin — luggage handling on the pier takes longer than people expect, and vehicle access to Capri itself is heavily restricted.",
    },
    parent: ROME,
    tags: ["rome", "naples", "amalfi-coast"],
    related: ["rome-to-amalfi-coast-transfer", "naples-to-sorrento-transfer", "rome-to-pompeii-transfer", "rome-to-positano-transfer"],
  }),
  route({
    slug: "rome-to-pompeii-transfer",
    from: "Rome",
    to: "Pompeii",
    km: "about 250 km",
    drive: "about 3 hours",
    road: "A1 and A3 motorways (toll)",
    alt: "Train to Naples, then the Circumvesuviana to Pompei Scavi — several changes and a longer day",
    pickups: "Fiumicino and Ciampino airports, Rome Termini station, Rome hotels",
    dropoffs: "Pompeii archaeological park entrances, Naples, Sorrento and Amalfi Coast hotels",
    access:
      "Vehicles use paid parking areas near the park entrances; a driver can drop you at the gate and meet you at a set time and place.",
    stops: [
      ["Herculaneum", "a compact site that pairs well with Pompeii"],
      ["Mount Vesuvius", "a viewpoint and short crater walk, weather permitting"],
      ["Oplontis (Torre Annunziata)", "a beautifully decorated Roman villa, much quieter than Pompeii"],
    ],
    insight: {
      heading: "Is a Rome day trip to Pompeii realistic?",
      text: "It is possible, but long: about six hours of driving return plus two to three hours on site. Many clients prefer to combine Pompeii with the Rome-to-Amalfi Coast transfer — see the ruins on the way and sleep by the sea — instead of returning to Rome the same day. Ask us for both options and we will lay out the timings.",
    },
    parent: ROME,
    tags: ["rome", "naples"],
    related: ["rome-to-amalfi-coast-transfer", "naples-to-pompeii-transfer", "rome-to-sorrento-transfer", "private-tours-italy"],
    service: "tour",
  }),
  route({
    slug: "rome-to-orvieto-transfer",
    from: "Rome",
    to: "Orvieto",
    km: "about 120 km",
    drive: "about 1 hour 30 minutes",
    road: "A1 motorway (toll), Orvieto exit",
    alt: "Regional trains from Rome Termini take about 1 hour 15 minutes to 1 hour 30 minutes; a funicular then climbs to the old town",
    pickups: "Rome hotels and stations, Fiumicino and Ciampino airports",
    dropoffs: "Orvieto old town, hotels and villas in Umbria and southern Tuscany",
    access:
      "The old town sits on a rock and is restricted to traffic; vehicles use parking at the base or edge and visitors take the funicular or shuttle, so we plan drop-off with your walking distance in mind.",
    stops: [
      ["Orvieto Duomo", "the Gothic cathedral is the reason most people visit"],
      ["Civita di Bagnoregio", "a hill village reached by a footbridge, about 25 km further"],
      ["Lake Bolsena", "a quiet volcanic lake near the A1"],
    ],
    insight: {
      heading: "A natural stop between Rome and Tuscany",
      text: "Orvieto adds only about two hours to a Rome-to-Florence or Rome-to-Siena drive, which makes it the easiest way to turn a transfer into a sightseeing day. Ask for the combined route and we will time the stop around your onward arrival.",
    },
    parent: ROME,
    tags: ["rome", "tuscany"],
    related: ["rome-to-florence-transfer", "rome-to-siena-transfer", "rome-to-assisi-transfer", "private-tours-italy"],
  }),
  route({
    slug: "rome-to-assisi-transfer",
    from: "Rome",
    to: "Assisi",
    km: "about 190 km",
    drive: "about 2 hours 15 minutes",
    road: "A1 motorway (toll), then Umbrian state roads",
    alt: "Direct and connecting trains run in roughly 2 to 2.5 hours; the station is below the town",
    pickups: "Rome hotels and stations, Fiumicino and Ciampino airports, Vatican-area hotels",
    dropoffs: "Assisi's basilicas and hotels, Perugia, Spello and other Umbrian towns",
    access:
      "Assisi's medieval centre is restricted; coaches and cars drop at designated points outside or at the edge of the walls, with a short uphill walk.",
    stops: [
      ["Spello", "a flower-lined medieval town a few minutes from Assisi"],
      ["Perugia", "Umbria's capital, with an escalator-linked old town"],
      ["Santa Maria degli Angeli", "the large basilica in the valley below Assisi"],
    ],
    insight: {
      heading: "Planning a pilgrim or faith-group visit",
      text: "The Basilica of St Francis has a dress code (covered shoulders and knees) and security checks, and mornings are the quietest. We recommend early arrivals for groups, a coach drop-off arranged in advance, and a clear meeting point for the return — the slope and cobblestones make the walk longer than the map suggests.",
    },
    vehicles:
      "For pilgrim and parish groups we quote minibuses and coaches with a designated drop-off point; smaller parties travel comfortably in vans.",
    parent: ROME,
    tags: ["rome"],
    related: ["rome-to-orvieto-transfer", "rome-to-florence-transfer", "group-transportation-italy", "group-travel-italy"],
    service: "group",
  }),
  route({
    slug: "rome-to-siena-transfer",
    from: "Rome",
    to: "Siena",
    km: "about 230 km",
    drive: "about 2 hours 45 minutes",
    road: "A1 motorway (toll) and the Siena expressway (RA3)",
    alt: "There is no direct high-speed train; rail connections via Florence or Chiusi take longer than driving",
    pickups: "Fiumicino and Ciampino airports, Rome Termini station, Rome hotels",
    dropoffs: "Siena hotels, Chianti and Val d'Orcia villas, San Gimignano",
    access:
      "Siena's historic centre is a restricted-traffic zone; the driver drops you at the closest permitted point and we tell you where beforehand.",
    stops: [
      ["Montepulciano", "a hilltop wine town known for Vino Nobile"],
      ["Pienza", "a Renaissance 'ideal town' in the Val d'Orcia"],
      ["San Quirico d'Orcia", "classic Tuscan scenery and cypress avenues"],
    ],
    insight: {
      heading: "Palio days and the Val d'Orcia route",
      text: "Siena's Palio horse race runs on 2 July and 16 August, when the centre closes to traffic and hotels fill early — book the transfer at the same time as your room. Outside those dates, the scenic Val d'Orcia route adds roughly an hour to 90 minutes and is usually worth it.",
    },
    parent: ROME,
    tags: ["rome", "tuscany"],
    related: ["rome-to-florence-transfer", "rome-to-orvieto-transfer", "tuscany-private-driver", "florence-to-chianti-private-driver"],
  }),
  route({
    slug: "rome-to-civitavecchia-cruise-port-transfer",
    from: "Rome",
    to: "Civitavecchia Cruise Port",
    h1: "Rome to Civitavecchia Cruise Port Transfer",
    km: "about 80 km from central Rome (about 65 km from Fiumicino Airport)",
    drive: "about 1 hour to 1 hour 15 minutes",
    road: "A12 motorway and the SS1 Aurelia",
    alt: "Regional trains run from Rome to Civitavecchia in about an hour, followed by a shuttle to the cruise terminals",
    pickups: "Fiumicino and Ciampino airports, Rome Termini station, Rome hotels",
    dropoffs: "The Civitavecchia cruise terminals (we confirm your ship's berth the day before)",
    access:
      "The port has several cruise terminals; vehicles reach the terminal gate and luggage is handed over at drop-off, with security checks at the terminal.",
    stops: [
      ["Tarquinia", "an Etruscan necropolis with painted tombs, about 25 km north of the port"],
      ["Cerveteri", "the Banditaccia Etruscan necropolis, about 45 km from Rome"],
      ["Santa Marinella", "a small coastal town for a relaxed pre-cruise lunch"],
    ],
    insight: {
      heading: "Cruise-day timing",
      text: "Aim to reach the terminal two to three hours before departure; embarkation usually closes about an hour before sailing, but check your cruise line's rules. On a shore day most ships stay eight to ten hours, so a round trip to Rome uses roughly three hours of driving and leaves limited sightseeing time — we build the schedule backwards from your all-aboard time.",
    },
    parent: ROME,
    tags: ["rome"],
    related: ["cruise-port-transfers-italy", "rome-airport-transfer", "rome-to-florence-transfer", "naples-cruise-port-transfer"],
    extraFaq: [
      {
        q: "What if my ship arrives early or my flight is delayed?",
        a: "We monitor both flight and ship timings. Give us the ship, terminal and all-aboard time and we adjust the pick-up so you arrive with a buffer.",
      },
    ],
  }),
  route({
    slug: "rome-to-venice-transfer",
    from: "Rome",
    to: "Venice",
    km: "about 530 km",
    drive: "about 5.5–6 hours",
    road: "A1, A14 and A13 motorways (toll)",
    alt: "High-speed trains take roughly 3 hours 45 minutes between the city centres",
    pickups: "Fiumicino and Ciampino airports, Rome Termini station, Rome hotels",
    dropoffs: "Piazzale Roma or Tronchetto, Mestre, Venice Marco Polo airport, Veneto villas",
    access:
      "Venice's historic centre is car-free: road transport ends at Piazzale Roma or Tronchetto, and guests continue by water taxi, vaporetto or on foot. We can pre-book a water-taxi leg with a partner.",
    stops: [
      ["Florence", "a lunch and Duomo stop roughly halfway"],
      ["Bologna", "Italy's food capital, with a walkable centre"],
      ["Padua", "Giotto's Scrovegni Chapel, which needs a timed booking"],
    ],
    insight: {
      heading: "Six hours by road is rarely the best plan",
      text: "For most travellers the train is faster and easier for the long leg. A private driver earns its place at either end (airport or hotel to the station) or when you split the trip with an overnight in Florence or Bologna. We are happy to say so if a train plus a short transfer suits you better.",
    },
    parent: ROME,
    tags: ["rome", "venice"],
    related: ["florence-to-venice-transfer", "milan-to-venice-transfer", "venice-airport-transfer", "rome-to-florence-transfer"],
  }),

  /* ───────────── FROM FLORENCE ───────────── */
  route({
    slug: "florence-to-venice-transfer",
    from: "Florence",
    to: "Venice",
    km: "about 260 km",
    drive: "about 3 hours",
    road: "A1 and A13 motorways (toll)",
    alt: "High-speed trains take about 2 hours between the city-centre stations",
    pickups: "Florence hotels and villas, Santa Maria Novella station, Pisa and Florence airports",
    dropoffs: "Piazzale Roma or Tronchetto, Mestre, Venice Marco Polo airport, Veneto villas",
    access:
      "Venice's historic centre is car-free; the vehicle stops at Piazzale Roma or Tronchetto and guests continue by water taxi or on foot.",
    stops: [
      ["Bologna", "a food-focused stop about halfway; allow 2 hours"],
      ["Ferrara", "a walled Renaissance city best seen by bike or on foot"],
      ["Padua", "the Scrovegni Chapel's Giotto frescoes (timed entry)"],
    ],
    insight: {
      heading: "Villa stays and the Veneto",
      text: "If you are staying in a Veneto villa (the Palladian villas around Vicenza and Treviso, for example) rather than in Venice itself, a private transfer beats the train: it delivers you to the door and lets you visit Venice as a day trip on your own schedule.",
    },
    parent: FLORENCE,
    tags: ["florence", "venice"],
    related: ["rome-to-venice-transfer", "venice-airport-transfer", "milan-to-venice-transfer", "rome-to-florence-transfer"],
  }),
  route({
    slug: "florence-to-cinque-terre-transfer",
    from: "Florence",
    to: "Cinque Terre",
    km: "about 170 km to La Spezia and Levanto",
    drive: "about 2 hours 15 minutes to 2 hours 45 minutes",
    road: "A11 and A12 motorways (toll)",
    alt: "Trains via Pisa to La Spezia or Levanto take roughly 2.5 to 3 hours with a change",
    pickups: "Florence hotels and villas, Santa Maria Novella station, Pisa airport",
    dropoffs: "La Spezia, Levanto, and the parking areas above Monterosso and other villages",
    access:
      "The five villages are largely car-free and connected by train, ferry and footpaths. Vehicles stop at edge-of-village parking, so guests with heavy luggage should choose a base such as La Spezia or Levanto.",
    stops: [
      ["Pisa", "the Leaning Tower is about an hour from Florence; a 90-minute stop is enough"],
      ["Lucca", "a walled town with a cycle-friendly rampart"],
      ["Carrara", "the marble quarries above the coast"],
    ],
    insight: {
      heading: "Luggage and the Cinque Terre",
      text: "The villages have steps, narrow lanes and crowded trains, so luggage is the main problem. We usually recommend a private transfer to La Spezia or Levanto, where your bags stay in a hotel while you explore the villages by train and ferry. Tell us your lodging and we will advise the best drop-off.",
    },
    parent: FLORENCE,
    tags: ["florence", "tuscany"],
    related: ["florence-to-chianti-private-driver", "milan-to-portofino-transfer", "rome-to-florence-transfer", "pisa-airport-transfer"],
  }),
  route({
    slug: "florence-to-chianti-private-driver",
    from: "Florence",
    to: "Chianti",
    noun: "Private Driver",
    km: "about 30 km to Greve and up to 70 km to the southern villages",
    drive: "about 40 minutes to 1 hour 15 minutes",
    road: "the SR222 Chiantigiana wine road and local provincial roads",
    alt: "Buses serve the main villages, but wine estates are usually off the bus routes",
    pickups: "Florence hotels and villas, Santa Maria Novella station, Pisa and Florence airports",
    dropoffs: "Wine estates, agriturismi, Greve in Chianti, Castellina, Radda and Panzano",
    access:
      "Estate roads are often unpaved and steep; your driver knows the approaches, and because you will be tasting wine, the driver drives.",
    stops: [
      ["Greve in Chianti", "an arcaded main square and wine shops"],
      ["Castellina in Chianti", "a fortified village with long views"],
      ["Castello di Brolio", "one of Chianti's oldest wine estates, with gardens"],
    ],
    insight: {
      heading: "Book Chianti by the day, not point to point",
      text: "A typical day is two estate visits with lunch and the drive between them. That works best as a full-day booking (8–10 hours) rather than a single transfer. Tell us how many estates you want and whether you prefer tastings or a cooking class, and we will propose a realistic plan — and take care of tasting reservations through partners.",
    },
    vehicles:
      "A van (up to 7 passengers) is the most comfortable for Chianti's winding roads; larger groups can travel in two vehicles or a minibus where estate access allows.",
    parent: FLORENCE,
    tags: ["florence", "tuscany"],
    related: ["tuscany-private-driver", "private-tours-italy", "rome-to-siena-transfer", "hourly-chauffeur-italy"],
    service: "chauffeur",
  }),

  /* ───────────── FROM NAPLES ───────────── */
  route({
    slug: "naples-to-amalfi-coast-transfer",
    from: "Naples",
    to: "Amalfi Coast",
    km: "about 68 km to Amalfi",
    drive: "about 1 hour 40 minutes",
    road: "A3 motorway (toll), then the SS163 Amalfi Drive",
    alt: "Train to Salerno then a ferry or SITA bus, or the Circumvesuviana to Sorrento then a SITA bus",
    pickups: "Naples Capodichino airport, Napoli Centrale station, the cruise port, Naples hotels",
    dropoffs: "Amalfi, Positano, Ravello, Praiano and other Coast towns",
    access:
      "Traffic restrictions and an alternate-licence-plate scheme apply across eleven Amalfi Coast municipalities, and some towns charge entry, parking and loading fees, which we itemise.",
    stops: [
      ["Pompeii", "adds 2–3 hours including entry"],
      ["Vietri sul Mare", "ceramics shops at the start of the Coast"],
      ["Sorrento", "a lemon-scented stop if you are arriving from the north side"],
    ],
    insight: {
      heading: "Choose the right last-mile vehicle",
      text: "The Coast road is narrow and busy in season, so the vehicle matters more than the distance. A sedan or van with a driver who holds the local permits reaches most hotels; a coach does not. We coordinate the final approach with local operators so you are not left on a roadside with your luggage.",
    },
    parent: NAPLES,
    tags: ["naples", "amalfi-coast"],
    related: ["rome-to-amalfi-coast-transfer", "naples-to-positano-transfer", "amalfi-coast-alternate-license-plates", "amalfi-coast-private-driver"],
  }),
  route({
    slug: "naples-to-positano-transfer",
    from: "Naples",
    to: "Positano",
    km: "about 61 km",
    drive: "about 1 hour 30 minutes",
    road: "A3 motorway (toll), then the SS163 Amalfi Drive",
    alt: "Train and bus combinations, or a seasonal ferry from Naples' Molo Beverello",
    pickups: "Naples Capodichino airport, Napoli Centrale station, the cruise port",
    dropoffs: "Positano hotels and villas, the Marina Grande area",
    access:
      "Positano's centre is largely car-free and restricted in season, and municipal entry, parking and loading fees apply. We confirm your hotel's access and the last few hundred metres beforehand.",
    stops: [
      ["Pompeii", "adds 2–3 hours including entry"],
      ["Sorrento", "a lunch stop across the peninsula road"],
      ["Praiano", "a quieter village with a view back towards Positano"],
    ],
    insight: {
      heading: "Positano's last few hundred metres",
      text: "Many Positano hotels sit on steps rather than at a road. Before you arrive we tell you where the vehicle stops, how many steps there are, and whether the hotel or a porter service handles luggage. That single piece of information prevents most arrival-day stress.",
    },
    parent: NAPLES,
    tags: ["naples", "amalfi-coast"],
    related: ["naples-to-amalfi-coast-transfer", "rome-to-positano-transfer", "amalfi-coast-alternate-license-plates", "amalfi-coast-wedding-transport"],
  }),
  route({
    slug: "naples-to-sorrento-transfer",
    from: "Naples",
    to: "Sorrento",
    km: "about 48 km",
    drive: "about 1 hour 15 minutes",
    road: "A3 motorway (toll), then the SS145 Sorrento road",
    alt: "The Circumvesuviana train takes about an hour from Naples, with luggage and crowding to manage",
    pickups: "Naples Capodichino airport, Napoli Centrale station, the cruise port, Naples hotels",
    dropoffs: "Sorrento hotels, Marina Piccola ferry port, Sant'Agnello and Massa Lubrense",
    access:
      "The SS145 is congested in season, and Sorrento's centre is partly pedestrian; we schedule around ferry times and hotel access.",
    stops: [
      ["Pompeii", "a common pause on the way; adds 2–3 hours"],
      ["Herculaneum", "a smaller and quieter alternative"],
      ["Vico Equense", "a scenic town on the way, known for its pizza"],
    ],
    insight: {
      heading: "Connecting to a Capri ferry",
      text: "If you are joining a Capri hydrofoil from Sorrento's Marina Piccola, tell us the departure time. We plan the transfer to arrive with a margin, because the SS145 can be slow on summer mornings and the pier has queues for luggage.",
    },
    parent: NAPLES,
    tags: ["naples", "amalfi-coast"],
    related: ["rome-to-sorrento-transfer", "naples-to-amalfi-coast-transfer", "naples-airport-transfer", "naples-to-pompeii-transfer"],
  }),
  route({
    slug: "naples-to-pompeii-transfer",
    from: "Naples",
    to: "Pompeii",
    km: "about 25–30 km",
    drive: "about 40–50 minutes",
    road: "A3 motorway (toll)",
    alt: "Circumvesuviana trains from Naples take roughly 35–40 minutes to Pompei Scavi",
    pickups: "Naples Capodichino airport, Napoli Centrale station, the cruise port, Naples hotels",
    dropoffs: "Pompeii park entrances, Herculaneum, Sorrento and Amalfi Coast hotels",
    access:
      "A driver can drop you at the park gate and meet you at a set time; parking near the entrances is paid and busy in the morning.",
    stops: [
      ["Herculaneum", "a compact, well-preserved Roman town, often paired with Pompeii"],
      ["Mount Vesuvius", "a crater walk and views over the bay"],
      ["Oplontis", "a quieter Roman villa near Torre Annunziata"],
    ],
    insight: {
      heading: "Combining Pompeii with the coast",
      text: "Pompeii sits directly on the route to Sorrento and the Amalfi Coast, so it is easy to add to a transfer. Book the entry tickets in advance for popular dates, wear comfortable shoes — the stone streets are uneven and there is little shade — and let us handle luggage in the vehicle while you explore.",
    },
    parent: NAPLES,
    tags: ["naples", "amalfi-coast"],
    related: ["rome-to-pompeii-transfer", "naples-to-sorrento-transfer", "naples-to-amalfi-coast-transfer", "private-tours-italy"],
    service: "tour",
  }),
  route({
    slug: "naples-cruise-port-transfer",
    from: "Naples",
    to: "Naples Cruise Port",
    h1: "Naples Cruise Port Transfer",
    km: "about 6 km from Capodichino airport and about 3 km from Napoli Centrale",
    drive: "about 20–30 minutes in normal traffic",
    road: "city streets and the tangenziale ring road",
    alt: "Buses and taxis run to the port; timing is unpredictable in Naples traffic",
    pickups: "Naples Capodichino airport, Napoli Centrale station, Naples hotels, Pompeii, Sorrento",
    dropoffs: "The Naples cruise terminals",
    access:
      "The terminals are in the busy port area next to the historic centre; we confirm your ship's berth the day before and plan the approach around port traffic.",
    stops: [
      ["Pompeii", "a popular shore-excursion destination, roughly 40–50 minutes away"],
      ["Herculaneum", "a shorter alternative for a half day"],
      ["Naples' historic centre", "the pizzerias and narrow lanes near the port"],
    ],
    insight: {
      heading: "Naples is a port of call, not just a starting point",
      text: "Ships arrive early in Naples, and the shore day is short. Most passengers choose either Pompeii or the Amalfi Coast, not both. Tell us your all-aboard time and preference and we will propose a realistic plan that returns you to the terminal with time to spare.",
    },
    parent: NAPLES,
    tags: ["naples"],
    related: ["cruise-port-transfers-italy", "naples-to-pompeii-transfer", "naples-airport-transfer", "rome-to-civitavecchia-cruise-port-transfer"],
    extraFaq: [
      {
        q: "Can you also collect us from the ship after the shore excursion?",
        a: "Yes — give us the ship, the terminal and your expected return time and we schedule the pick-up so you arrive back before the all-aboard deadline.",
      },
    ],
  }),

  /* ───────────── FROM MILAN / LAKES ───────────── */
  route({
    slug: "milan-to-lake-como-transfer",
    from: "Milan",
    to: "Lake Como",
    km: "about 50 km to Como and about 80 km to Bellagio",
    drive: "about 1 hour to Como and 1 hour 45 minutes to Bellagio",
    road: "A9 motorway (toll) to Como, then lakeside roads",
    alt: "Trains from Milan run to Como in roughly 40–60 minutes; ferries and buses continue along the lake",
    pickups: "Milan hotels and stations, Malpensa, Linate and Bergamo airports",
    dropoffs: "Como, Cernobbio, Bellagio, Tremezzo, Varenna and lakeside villas",
    access:
      "Lakeside villages have narrow roads, restricted zones and little parking, and Como's centre has a restricted-traffic zone. Villa hotels often have their own driveways, which we confirm with the property.",
    stops: [
      ["Como", "the Duomo and the funicular to Brunate for lake views"],
      ["Cernobbio", "elegant villas and lakeside promenades"],
      ["Villa del Balbianello (Lenno)", "a famous lakeside villa reached by short boat or walk; timed visits"],
    ],
    insight: {
      heading: "Combine the car with the ferry",
      text: "Lake ferries are scenic but slow, and hotels are often across the water from the road. A good plan is to drive to a ferry landing and cross by boat, or to take the ferry between villages and let the driver carry the luggage around the lake. Tell us where you are staying and we will propose the fastest reliable combination.",
    },
    parent: MILAN,
    tags: ["milan", "lake-como"],
    related: ["malpensa-to-lake-como-transfer", "malpensa-to-bellagio-transfer", "lake-como-wedding-transport", "milan-to-verona-transfer"],
  }),
  route({
    slug: "malpensa-to-lake-como-transfer",
    from: "Malpensa Airport",
    to: "Lake Como",
    km: "about 45–55 km to Como",
    drive: "about 50–60 minutes",
    road: "A8 and A9 motorways (toll)",
    alt: "Rail and bus combinations exist but usually involve changes; a private transfer is direct and door to door",
    pickups: "Malpensa Terminal 1 and Terminal 2",
    dropoffs: "Como, Cernobbio, Menaggio, Bellagio (via ferry or road), Tremezzo and lakeside villas",
    access:
      "Como's centre has restricted-traffic zones and lakeside villages have narrow roads; we confirm the last stretch with your hotel or villa before you fly.",
    stops: [
      ["Como", "a lunch stop by the lake and the Duomo"],
      ["Cernobbio", "a short detour to see the lakeside villas"],
      ["Varese", "a quieter stop with a park and villa on the way from Malpensa"],
    ],
    insight: {
      heading: "Arrival waves for wedding and group guests",
      text: "When many guests land on different flights, we run arrival waves from Malpensa: a vehicle leaves when it is full or after a set waiting time, and the schedule is shared with the planner. That works better than individual taxis, keeps the lake roads uncongested and puts everyone at the venue when the timeline needs them.",
    },
    parent: MILAN,
    tags: ["milan", "lake-como"],
    related: ["malpensa-airport-transfer", "malpensa-to-bellagio-transfer", "lake-como-wedding-transport", "milan-to-lake-como-transfer"],
    extraFaq: [
      {
        q: "Which Malpensa terminal will my driver meet me at?",
        a: "We meet you in the arrivals hall of the terminal your flight uses (Terminal 1 or Terminal 2). Your voucher confirms the meeting point once your flight details are in.",
      },
    ],
  }),
  route({
    slug: "malpensa-to-bellagio-transfer",
    from: "Malpensa Airport",
    to: "Bellagio",
    km: "about 95–105 km",
    drive: "about 1 hour 45 minutes to 2 hours 15 minutes",
    road: "A8 and A9 motorways (toll), then lakeside roads",
    alt: "Train or bus to Como and Lecco, then a ferry or bus — several changes with luggage",
    pickups: "Malpensa Terminal 1 and Terminal 2",
    dropoffs: "Bellagio hotels and villas, Varenna, Menaggio and Tremezzo ferry landings",
    access:
      "Bellagio sits at the tip of a peninsula served by a narrow road; parts of the village are pedestrian, and hotels may be up steps from the nearest drop-off point.",
    stops: [
      ["Como", "a stop before the lakeside stretch, with lunch by the water"],
      ["Villa Carlotta (Tremezzo)", "gardens across the water from Bellagio"],
      ["Menaggio", "a lively village with a ferry to Bellagio"],
    ],
    insight: {
      heading: "Ferry or road for the last stretch?",
      text: "In peak season the lakeside road can be slow, and it is sometimes faster to drive to Menaggio, Cadenabbia or Varenna and cross to Bellagio by ferry in about 15 minutes. We choose based on the day, the traffic and your luggage, and plan the crossing times so you are not waiting on the pier.",
    },
    parent: MILAN,
    tags: ["milan", "lake-como"],
    related: ["malpensa-to-lake-como-transfer", "milan-to-lake-como-transfer", "lake-como-wedding-transport", "malpensa-airport-transfer"],
  }),
  route({
    slug: "milan-to-venice-transfer",
    from: "Milan",
    to: "Venice",
    km: "about 270 km",
    drive: "about 3–3.5 hours",
    road: "A4 motorway (toll)",
    alt: "High-speed trains take roughly 2 hours 30 minutes between the city centres",
    pickups: "Milan hotels and stations, Malpensa, Linate and Bergamo airports",
    dropoffs: "Piazzale Roma or Tronchetto, Mestre, Venice Marco Polo airport, Veneto villas",
    access:
      "Venice's historic centre is car-free; the vehicle stops at Piazzale Roma or Tronchetto and guests continue by water taxi, vaporetto or on foot.",
    stops: [
      ["Sirmione (Lake Garda)", "a peninsula town at the southern tip of the lake"],
      ["Verona", "the Arena and Juliet's House, about halfway"],
      ["Vicenza", "Palladian architecture in the city and villas"],
    ],
    insight: {
      heading: "Stopping at Lake Garda or Verona",
      text: "The A4 passes close to Lake Garda and Verona, so a stop adds less time than most drivers expect. A midday stop in Sirmione or Verona breaks up the drive and can be built into the price. Tell us what you want to see and we will fit it around your check-in time in Venice.",
    },
    parent: MILAN,
    tags: ["milan", "venice"],
    related: ["milan-to-verona-transfer", "florence-to-venice-transfer", "venice-airport-transfer", "rome-to-venice-transfer"],
  }),
  route({
    slug: "milan-to-verona-transfer",
    from: "Milan",
    to: "Verona",
    km: "about 160 km",
    drive: "about 1 hour 45 minutes",
    road: "A4 motorway (toll)",
    alt: "High-speed and regional trains take roughly 1 hour 15 minutes to 1 hour 30 minutes",
    pickups: "Milan hotels and stations, Malpensa, Linate and Bergamo airports",
    dropoffs: "Verona hotels, Verona Fiere, Lake Garda towns, Valpolicella wineries",
    access:
      "Verona's historic centre is a restricted-traffic zone; drop-off is at the closest permitted point, and the trade-fair district has its own access and parking.",
    stops: [
      ["Lake Garda", "Sirmione or Peschiera for a lakeside lunch"],
      ["Bergamo", "the upper town's medieval walls, roughly 50 km from Milan"],
      ["Valpolicella", "wineries north of Verona, best booked in advance"],
    ],
    insight: {
      heading: "Vinitaly and Arena opera weeks",
      text: "Verona hosts Vinitaly each April and a summer opera season in the Roman Arena; in those weeks hotels fill and roads around the trade-fair area and old town are congested. Book the vehicle at the same time as your room, and let us schedule pick-ups outside the busiest windows.",
    },
    parent: MILAN,
    tags: ["milan", "verona"],
    related: ["milan-to-venice-transfer", "milan-fair-transfers", "milan-to-lake-como-transfer", "verona"],
  }),
  route({
    slug: "milan-to-portofino-transfer",
    from: "Milan",
    to: "Portofino",
    km: "about 170–180 km",
    drive: "about 2 hours 15 minutes to 2 hours 45 minutes",
    road: "A7 and A12 motorways (toll), then the coastal road from Rapallo or Santa Margherita",
    alt: "Trains run to Santa Margherita Ligure or Rapallo in roughly 2 to 2.5 hours, then a bus, taxi or boat",
    pickups: "Milan hotels and stations, Malpensa, Linate and Bergamo airports",
    dropoffs: "Portofino, Santa Margherita Ligure, Rapallo and Camogli",
    access:
      "Portofino is a small village with a narrow access road and limited parking, and vehicle restrictions can apply in peak season; drop-off may be near the village entrance with a short walk.",
    stops: [
      ["Genoa", "the old port and historic centre"],
      ["Camogli", "a colourful fishing village with a pebble beach"],
      ["Rapallo", "a cable car up to a hilltop sanctuary"],
    ],
    insight: {
      heading: "Arriving by boat",
      text: "A scenic alternative is to drive to Santa Margherita Ligure or Rapallo and take a short boat to Portofino. It avoids the narrow coastal road at busy times, and we can arrange the timing with the ferry or a private boat through partners.",
    },
    parent: MILAN,
    tags: ["milan"],
    related: ["milan-to-lake-como-transfer", "florence-to-cinque-terre-transfer", "milan-to-venice-transfer", "private-chauffeur-italy"],
  }),
];
